import type { ModelProfile, ModelRoutingRule } from "@jarvis/types";

export const DEFAULT_PROFILES: ModelProfile[] = [
  {
    id: "mimo-2.5-pro",
    provider: "mimo",
    modelName: "mimo-v2.5-pro",
    displayName: "MiMo 2.5 Pro",
    capabilities: {
      text: true,
      streaming: true,
      toolCalling: true,
      vision: false,
      audioInput: false,
      tts: false,
      jsonMode: true,
      longContext: true,
    },
    limits: { contextWindow: 1000000, maxOutputTokens: 8192 },
    cost: { input: 0, output: 0 },
  },
  {
    id: "mimo-2.5-fast",
    provider: "mimo",
    modelName: "mimo-v2.5-fast",
    displayName: "MiMo 2.5 Fast",
    capabilities: {
      text: true,
      streaming: true,
      toolCalling: true,
      vision: false,
      audioInput: false,
      tts: false,
      jsonMode: true,
      longContext: false,
    },
    limits: { contextWindow: 128000, maxOutputTokens: 4096 },
    cost: { input: 0, output: 0 },
  },
  {
    id: "groq-llama",
    provider: "groq",
    modelName: "llama-3.3-70b-versatile",
    displayName: "Groq Llama 3.3 70B",
    capabilities: {
      text: true,
      streaming: true,
      toolCalling: true,
      vision: false,
      audioInput: false,
      tts: false,
      jsonMode: true,
      longContext: false,
    },
    limits: { contextWindow: 128000, maxOutputTokens: 32768 },
    cost: { input: 0, output: 0 },
  },
  {
    id: "openrouter-default",
    provider: "openrouter",
    modelName: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet 4 (OpenRouter)",
    capabilities: {
      text: true,
      streaming: true,
      toolCalling: true,
      vision: true,
      audioInput: false,
      tts: false,
      jsonMode: true,
      longContext: true,
    },
    limits: { contextWindow: 200000, maxOutputTokens: 8192 },
    cost: { input: 3, output: 15 },
  },
  {
    id: "local-ollama",
    provider: "local",
    modelName: "llama3.2",
    displayName: "Ollama Local",
    capabilities: {
      text: true,
      streaming: true,
      toolCalling: false,
      vision: false,
      audioInput: false,
      tts: false,
      jsonMode: true,
      longContext: false,
    },
    limits: { contextWindow: 32000, maxOutputTokens: 4096 },
    cost: { input: 0, output: 0 },
  },
];

export const DEFAULT_ROUTING_RULES: ModelRoutingRule[] = [
  {
    taskType: "fast",
    modelId: "groq-llama",
    conditions: { expectedAnswerLength: "short" },
  },
  {
    taskType: "toolAgent",
    modelId: "mimo-2.5-pro",
    conditions: { requiresToolCalling: true },
  },
  {
    taskType: "reasoning",
    modelId: "mimo-2.5-pro",
    conditions: { requiresLongContext: true },
  },
  {
    taskType: "private",
    modelId: "local-ollama",
    conditions: { requiresPrivacy: true },
  },
  {
    taskType: "chat",
    modelId: "mimo-2.5-pro",
  },
];
